### ISSUE TITLE
Some Problem When I Run The Code

### ISSUE THREAD

**Issue by HIT1180300227** [EnergyBasedFlowClassifier/EFC#1]
when I run the usage_example.py after following the built method in the readme,there occurs some error:
![error](https://user-images.githubusercontent.com/61338157/144563340-1e6bc5e9-b3d9-4551-aee1-85adc1f975fe.png)

Is this problem due to some wrong build procedure?

**Comment by munak98** [comment]
Hello!
We sincerely apologize for the long delay in responding to your issue. This repository was out of maintenance because it was just to store the codes used in our experiments. Indeed, this problem you encountered was a bug in the Cython code. This issue has been fixed in the EFC software package, which is actually the version we recommend for use as it was created for external users. Here's the link to the package if you're still interested: https://github.com/EnergyBasedFlowClassifier/EFC-package
